import pandas as pd
df=pd.read_csv('imdb_top_250.csv')
# print(df)
# print("First 5 rows are")
# print(df.head())
# print("\n The analysis of the dataset is")
# print(df.describe())
# print("\n The size of the dataset is")
# print(df.shape)
# print("\n The information of dataset is")
# print(df.info())
# df1=df.head()
# print(df1)
# df1.to_csv('new_imdb.csv',index=False)
# print("\n All dropout cases are")
# print(df[df['Year']==2012])
# print(df.dropna())